### ISSUE TITLE
PTPRZ1-MET

### ISSUE THREAD

**Issue by BadSeby** [murphycj/agfusionweb-react#4] opened 2020-06-10 15:44 UTC
Dear Dr. Murphy,

I'm Sebastiano Di Bella,
 
I am attempting to draw the in-frame validated PTPRZ1-MET fusion described in the paper published by Bao et al. (Https://genome.cshlp.org/content/24/11/1765.long) using AGFusion.
As reported in the article, U118 and LN18 cell lines harbored the PTPRZ1-MET fusion, involving exon 1 to 2 of PTPRZ1 fused with exon 2 to 21 of MET.
Interrogating hg19 and using the breakpoint 121608184 (ENST00000393386) for PTPRZ1 and 116339125 (ENST00000397752) for MET, the resulting fusion is defined as 'out-of-frame' by AGFusion. Conversely, manually analysis reported in the enclosed word file has highlighted that the identified PTPRZ1-MET fusion produced an in-frame protein product. The issue is probably related to the UTR region included in exon 2 of MET gene. This UTR portion is not reported in AGfusion and consequently the reading frame is completely disrupted.
 
I would be greatful if you could help us
 
Looking forward to hearing from you

Thanks a lot in advance & Best Regards
 
Sebastiano

[FUSION PTPRZ1-MET.docx](https://github.com/murphycj/agfusionweb-react/files/4759645/FUSION.PTPRZ1-MET.docx)

**Comment by murphycj** [comment] 2020-06-11 01:12
Hi Sebastiano,

Thank you for reporting the issue. I will take a look into it and get back to you soon.

Best,
Charlie

**Comment by murphycj** [comment] 2020-06-13 23:02
Sebastiano,

I patched a fix to the issue. Please try the website again and see if it works as intended for you.

Best,
Charlie

**Comment by BadSeby** [comment] 2020-06-15 08:22
Hi Charlie,
it's perfect for me, thanks!

Will you also update the script python?

**Comment by murphycj** [comment] 2020-06-15 23:04
Great! I'll close this issue then. I'll try to fix the python script sometime later this week when I have time. Again, thank you for reporting the issue.

**Closed as completed by murphycj** 2020-06-15 23:04 UTC
Labels: bug
